### ISSUE TITLE
Using base in an ImplementationGuide

### ISSUE THREAD

**Issue by KevinMayfield** [INTEROPen/careconnect-base-stu3#58]
The IG Guide (resource) has a baseUrl of https://fhir.hl7.org.uk/STU3/ this is to match the baseUrl of the resources it contains. 

The IG is currently hosted on https://hl7-uk.github.io/UK-STU3 (and the HL7 UK INTEROPen CareConnect Reference Server is hosted on https://fhir.hl7.org.uk/STU3/).  

When this IG is used by another IG the IGPublisher fails as it expects both the both profiles and implementation guide to use the same baseUrl.

**Comment by KevinMayfield** [comment]
This is sounds like a high severity issue as it prevents the IG being used in other IG's (which is one of the core aims).

**Comment by DaveBarnet** [comment]
Kevin - a lot of these errors you point to are from the SNOMED ECL statements (for example 
"CareConnect-AllergyCertainty-1 | error | Error from server: The filter "constraint = (385434005 
 | Improbable diagnosis | OR 2931005 | Probable diagnosis | OR 255545003 | Definite | OR 410605003  | Confirmed present |)" was not understood in the context of http://snomed.info/sct"

If you take the constraint (385434005  | Improbable diagnosis | OR 2931005 | Probable diagnosis | OR 255545003 | Definite | OR 410605003  | Confirmed present |) 
and run this through a URL encoder you get 

(385434005%20%7CImprobable%20diagnosis%7C%20OR%202931005%20%7CProbable%20diagnosis%7C%20OR%20255545003%20%7CDefinite%7C%20OR%20410605003%20%7CConfirmed%20present%7C) 

& then fire this at ontoserver 
https://ontoserver-dev.dataproducts.nhs.uk/fhir/ValueSet/$expand?url=http://snomed.info/sct/999000031000000106%3Ffhir_vs=ecl/(385434005%20%7CImprobable%20diagnosis%7C%20OR%202931005%20%7CProbable%20diagnosis%7C%20OR%20255545003%20%7CDefinite%7C%20OR%20410605003%20%7CConfirmed%20present%7C)

you get the results back as expected from the ECL. So I'm not sure it's fair to call this an error on the valueSet definition?

**Comment by KevinMayfield** [comment]
Comment above attached to wrong issue. Relates to #11

**Comment by KevinMayfield** [comment]
Copied text over to #11

**Comment by KevinMayfield** [comment]
Use packageId instead. 
```xml
 <dependsOn>
    <uri value="https://fhir.hl7.org.uk/STU3/ImplementationGuide/hl7.uk.base" />
    <packageId value="hl7.uk.base"/>
    <version value="dev"/>
  </dependsOn>
```
